projects/webptspy/webpts/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from tproject.views.project import ProjectListView
from account.views import page_403, page_404, page_500


urlpatterns = [
    # 首页
    url(r'^$', ProjectListView.as_view(), name="index"),
    url(r'^admin/', admin.site.urls),
    # 项目相关的路由
    url(r'^project/', include('tproject.urls.project', namespace='project')),
    # 用户相关的路由
    url(r'^user/', include('account.urls', namespace='user')),
    # 网站api
    url(r'^api/1.0/', include('webpts.urls_api', namespace="api")),
    # 测试用例
    url(r'^case/', include('tcase.urls.case', namespace="case")),
    # execute相关的路由
    url(r'^execute/', include('tcase.urls.execute', namespace='execute')),
]


handler403 = page_403
handler404 = page_404
handler500 = page_500

projects/webptspy/apps/tcase/models.py
# -*- coding:utf-8 -*-
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from account.models import UserProfile
from tproject.models import Project
from utils.storage import ImageStorage
# Create your models here.


@python_2_unicode_compatible
class Case(models.Model):
    """
    性能测试用例Model
    """
    # 状态选项，如果是running，就不创建新的执行
    STATUS_CHOICES = (
        ('draft', "草稿"),
        ('created', "已创建"),
        ('ready', '准备就绪'),
        ('running', "执行中"),
        ('failure', "有错误"),
        ('success', "成功执行"),
        ('stoped', '已停止'),
        ('delete', "已删除")
    )
    WAY_CHOICES = (
        ('shiwu', "事务"),
        ('code', '代码')
    )
    # 当测试用例刚保存，状态为created
    # 创建好了case_id.py文件，修改状态为`ready`状态, 当新创建了execute也改成ready
    # 当开始execute的同时，也修改case的状态为：running
    # execute执行完毕，同时也修改Case的状态为：success / failure / stoped
    # Case还可以删除， 待优化

    project = models.ForeignKey(to=Project, verbose_name="项目")
    name = models.CharField(max_length=100, verbose_name="测试用例")
    desc = models.CharField(max_length=512, blank=True, verbose_name="描述")
    user = models.ForeignKey(to=UserProfile, blank=True, verbose_name="添加者")

    # 编码方式
    way = models.CharField(max_length=10, choices=WAY_CHOICES, default='shiwu',
                           verbose_name="编码方式")
    # code主要是：get、post访问页面的函数
    code = models.TextField(blank=True, null=True, verbose_name="测试代码")
    # 保存下状态
    status = models.CharField(choices=STATUS_CHOICES, max_length=10,
                              verbose_name="状态", default="created")
    # 保存下最新的execute_id
    execute_id = models.IntegerField(blank=True, null=True,
                                     verbose_name="最近执行")
    # 有些脚本需要cookie信息
    cookies = models.CharField(max_length=512, blank=True, default="")
    add_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    # 由于测试用例后续会修改，需要记录下修改的时间
    updated_time = models.DateTimeField(auto_now=True, verbose_name="更新时间",
                                        blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "测试用例"
        verbose_name_plural = verbose_name

        # 设置Object权限
        # Django会自动添加：add_case, change_case, delete_case权限
        # 通过user.has_perm('tcase.add_case')
        permissions = (
            ('can_view_case', '查看测试用例'),
            ('can_run_case', '执行测试用例'),
        )


@python_2_unicode_compatible
class Execute(models.Model):
    """
    测试用例执行Model
    """
    STATUS_CHOICES = (
        ('created', "已创建"),
        ('ready', "已准备"),
        ('running', "运行中"),
        ('failure', "失败"),
        ('success', "成功"),
        ('stoped', "已停止")
    )
    # Case执行，先创建Execute，这个时候状态是created
    # 进入执行，状态变为ready
    # 开始执行，修改状态为：running
    # locust触发了stop事件的时候，修改状态为：success / failure / stoped

    # name规范：测试用例版本N第n次执行
    name = models.CharField(max_length=100, blank=True, verbose_name="执行名字")
    case = models.ForeignKey(to=Case, verbose_name="测试用例")
    user = models.ForeignKey(to=UserProfile, blank=True, null=True,
                             verbose_name="执行者")
    # 状态
    status = models.CharField(max_length=10, verbose_name="状态",
                              default="created")
    port = models.IntegerField(default=8089, verbose_name="locust端口号")
    time_start = models.DateTimeField(blank=True, null=True,
                                      verbose_name="开始时间")
    time_end = models.DateTimeField(blank=True, null=True,
                                    verbose_name="结束时间")

    def __str__(self):
        # return '{0}:测试结果'.format(self.code.case.name)
        return self.name

    class Meta:
        verbose_name = "执行测试"
        verbose_name_plural = "执行测试列表"

        # 添加权限
        permissions = (
            ('can_view_report', '查看测试报告'),
        )


@python_2_unicode_compatible
class Shiwu(models.Model):
    """
    事务Modele
    """
    METHOD_CHOICES = (
        ('get', 'GET'),
        ('post', 'POST'),
        ('put', 'PUT'),
        ('delete', 'DELETE')
    )
    name = models.CharField(max_length=100, verbose_name="事务名")
    project = models.ForeignKey(to=Project, verbose_name="项目")
    # 用例与事务是多对多关系 一个case有多个shiwu，一个shiwu可以用到多个用例中
    # 实务获取case: obj_shiwu.cases.all()
    # 测试用例获取shiwu：obj_case.shiwu_set.all()
    cases = models.ManyToManyField(to=Case, verbose_name="用例")
    is_startup = models.BooleanField(default=False, verbose_name="启动准备")
    method = models.CharField(max_length=10, choices=METHOD_CHOICES,
                              verbose_name="请求方法", default='get')
    url = models.CharField(max_length=100, verbose_name="请求网址")
    cycle = models.BooleanField(default=True, verbose_name="数据可循环")
    body = models.TextField(blank=True, null=True, verbose_name="请求内容")
    user = models.ForeignKey(to=UserProfile, blank=True, null=True,
                             default='', verbose_name="添加者")
    # 请求事务可以克隆，每个人员维护自己的事务
    # 添加测试用例页面可以clone别人的事务
    is_clone = models.BooleanField(default=False, verbose_name="克隆")
    # 克隆母体，因为源头与克隆事务不互相影响，这里不用外键，而是仅保存源事务的ID
    parent = models.IntegerField(blank=True, null=True, verbose_name="源头")
    add_time = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "请求事务"
        verbose_name_plural = verbose_name

        # 添加权限
        permissions = (
            ('can_view_shiwu', '查看事务'),
        )

projects/webptspy/apps/tcase/forms.py
# -*- coding:utf-8 -*-
from django import forms

from .models import Case, Shiwu


class CaseForm(forms.ModelForm):
    """
    测试用例Model Form
    """
    class Meta:
        model = Case
        fields = ('project', 'name', 'desc', 'way', 'code', 'status', 'cookies')


class ShiwuForm(forms.ModelForm):
    """
    请求事务Model Form
    """
    class Meta:
        model = Shiwu
        fields = ('name', 'project', 'is_startup', 'method', 'url', 'cycle',
                  'body')


class ShiwuEditForm(forms.Form):
    """
    事务编辑Form
    """
    name = forms.CharField(label="事务名", max_length=100)
    project = forms.IntegerField(widget=forms.Select, label="项目")
    is_startup = forms.BooleanField(widget=forms.CheckboxInput, label="启动准备")
    method = forms.CharField(widget=forms.Select, label="请求类型")
    url = forms.CharField(max_length=100, label="网址")
    cycle = forms.BooleanField(widget=forms.CheckboxInput, label="数据可循环")

projects/webptspy/apps/tcase/views/case.py
# -*- coding:utf-8 -*-
import os
from datetime import datetime

from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View
from django.conf import settings
from django.core.paginator import Paginator
from django.db.models import Q
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse

from tproject.models import Project
from utils.mixins import LoginRequiredMixin
from utils.make_case_code import make_case_code
from utils.make_case_file import make_case_file
from utils.paginator import get_page_num_list
from ..models import Case, Execute, Shiwu
from ..forms import CaseForm

# Create your views here.


class CaseListView(View):
    """
    网站首页View
    """
    def get(self, request, page=None):
        all_case = Case.objects.all()
        # 关键词过滤
        keyword = request.GET.get('keyword', '')
        if keyword :
            projects = Project.objects.filter(Q(name__icontains=keyword) |
                                              Q(address__icontains=keyword) |
                                              Q(name_en__icontains=keyword))
            all_case = all_case.filter(Q(project__in=projects) |
                                       Q(name__icontains=keyword))

        # 分页处理
        if page:
            page_num = int(page)
        else:
            page_num = 1
        p = Paginator(all_case, 10)
        cases = p.page(page_num)

        # 获取分页器的页码列表，得到当前页面最近的7个页码列表
        page_num_list = get_page_num_list(p.num_pages, page_num, 7)

        return render(request, 'case/list.html', {
            'all_case': cases,
            'page_num_list': page_num_list,
            'last_page': p.num_pages,
            'keyword': keyword,
        })


class CaseExecuteView(LoginRequiredMixin, View):
    """
    执行测试用例View
    执行测试用例需要做的事情：
    1、判断在代码根目录下的 ../scripts/是否存在cese_id.py的文件
        1-1：如果存在，跳过
        1-2：如果不存在，则创建文件
    2、判断case是否有execute_id，没有就创建
    3、根据execute_id获取对应的execute的状态，根据状态做不同的处理
        3-1：如果execute.status是running那么就跳转到这个执行
        3-2: 如果execute.status已经是stoped, falure, sucess状态，
            我们就需要重新创建个新的执行
        3-3：更新相关的状态、跳转到新的执行
    """
    def get(self, request, pk):
        # 根据pk获取到对应的case
        case = get_object_or_404(Case, pk=pk)
        # 这里还需要对user进行权限判断，是否有执行的权限：
        user = request.user
        # 权限判断
        # 需要拥有can_run_case的权限才可以访问
        if not user.has_perm('tcase.can_run_case'):
            raise PermissionDenied

        # 第一步：先判断case_id.py的文件是否存在
        base_dir_parent = os.path.dirname(settings.BASE_DIR)
        scripts_dir = os.path.join(base_dir_parent, 'scripts')
        case_file_name = 'case_%s.py' % pk
        case_file_path = os.path.join(scripts_dir, case_file_name)
        # 判断文件是否存在
        if os.path.exists(case_file_path):
            # 如果存在，删除文件
            os.remove(case_file_path)
        # 每次都写入新的文件，以为脚本中可能会有cookies
        host_target = request.META['HTTP_HOST']
        # 根据Case的编码方式 way字段
        if case.way == 'code':
            case_code = case.code
            # 如果代码中有COOKIES_FOR_REPLACE 且 cookies不为空，就替换
            # 注意："COOKIES_FOR_REPLACE" 以后在脚本中的set_up中的cookie就写成这个
            if case_code.find("COOKIES_FOR_REPLACE") > 0 and case.cookies:
                case_code = case_code.replace("COOKIES_FOR_REPLACE", case.cookies)
        else:
            # 其它方式就是使用shiwu的模式编码
            case_code = make_case_code(case)
        result = make_case_file(
            code_content=case_code,
            file_name=case_file_name,
            case_id=pk,
            host_target=host_target
        )

        # 如果result是False就需要抛出500错误:报个403吧
        if not result:
            raise PermissionDenied

        # 第二步：判断execute_id是否存在, 判断是否要创建新的execute
        need_create_execute = False
        execute = None
        # 判断是否存在execute id
        if case.execute_id:
            # 有execute_id字段 还需要判断这个execute是否在运行中
            execute = Execute.objects.filter(pk=case.execute_id).last()
            if execute and execute.status in ['created', 'ready', 'running']:
                # 跳转到execute的报告页面
                return redirect(to='/execute/%d/' % execute.pk)
            else:
                # 如果不是运行中，那么就直接创建一个新的执行吧
                need_create_execute = True
        else:
            need_create_execute = True

        if need_create_execute:
            # 创建新的execute
            execute_name = case.name + datetime.now().strftime(
                "%Y%m%d%H%M%S")
            # 同时要记录是谁执行的
            execute = Execute.objects.create(case=case, name=execute_name,
                                             user=user)
            case.execute_id = execute.id
            case.save()
        # 跳转去execute的页面
        return redirect(to='/execute/%d/' % execute.pk)


class CaseAddView(LoginRequiredMixin, View):
    """
    添加测试用例View
    需要登陆
    """
    def get(self, request):
        # 权限判断：需要tcase.add_case的权限
        if not request.user.has_perm('tcase.add_case'):
            raise PermissionDenied

        # 先获取到所有项目
        all_projects = Project.objects.all()
        # 获取get project 的id, 前台根据这个选中默认的project
        project = request.GET.get('project', '')
        # 也可以根据id或者英文名字匹配出第一个项目
        target_project = None
        if project:
            if project.isdigit():
                target_project = Project.objects.filter(pk=project).first()
            else:
                target_project = Project.objects.filter(
                    name_en__icontains=project).first()
                # 如果传入了project字符，也对项目进行过滤一下
                all_projects = all_projects.filter(name_en__icontains=project)

        target_project_id = 0
        if target_project:
            target_project_id = target_project.pk

        return render(request, 'case/add.html', {
            'all_projects': all_projects,
            'target_project': target_project_id
        })

    def post(self, request):
        # post添加case
        # 因为case需要user字段，但是user_id不从前端传入，直接去request.user.pk
        # 这样在实例化CaseForm的时候，传入个instance对象
        case_form = CaseForm(request.POST, instance=Case(user_id=request.user.pk))
        # print(case)
        # print(request.POST.getlist('shiwu'))

        # 权限判断：需要tcase.add_case的权限
        if not request.user.has_perm('tcase.add_case'):
            raise PermissionDenied

        if case_form.is_valid():
            # 传入的数据ok
            # print(case.data, case.data['project'])
            case = case_form.save()
            # 获取到shiwu的列表
            shiwu_id_list = request.POST.getlist('shiwu')
            # 给case添加请求事务
            shiwu_list = Shiwu.objects.filter(pk__in=shiwu_id_list)
            for shiwu in shiwu_list:
                case.shiwu_set.add(shiwu)
        else:
            # 传入的数据不正确
            print(case_form.errors)
        return redirect(reverse('project:detail', args=[case_form.data['project']]))


class CaseEditView(LoginRequiredMixin, View):
    """
    测试用例编辑View
    """
    def get(self, request, pk):
        # 权限判断：需要tcase.change_case的权限
        if not request.user.has_perm('tcase.change_case'):
            raise PermissionDenied

        # 先获取到case实例对象
        case = get_object_or_404(Case, pk=pk)
        return render(request, 'case/edit.html', {
            'case': case,
            'status_choices': Case.STATUS_CHOICES,
        })

    def post(self, request, pk):
        # 权限判断：需要tcase.change_case的权限
        if not request.user.has_perm('tcase.change_case'):
            raise PermissionDenied

        # 先获取到case实例对象
        case = get_object_or_404(Case, pk=pk)
        # 实例化CaseForm
        case_form = CaseForm(request.POST, instance=case)

        if case_form.is_valid():
            # 保存新的case
            case_new = case_form.save()
            # 获取到shiwu的列表
            shiwu_id_list = request.POST.getlist('shiwu')
            # 给case添加请求事务
            shiwu_list = Shiwu.objects.filter(pk__in=shiwu_id_list)
            # 清楚开始所有的事务列表，重新添加一次
            case_new.shiwu_set.clear()
            for shiwu in shiwu_list:
                case_new.shiwu_set.add(shiwu)
            return redirect(to=reverse('project:detail',
                                       args=(case_new.project_id,)))
        else:
            # 验证失败
            return redirect(to=reverse('case:edit', args=(pk,)))

projects/webptspy/templates/case/edit.html
{% extends 'base.html' %}
{% block title %}编辑测试用例-{{ case.name }} | 性能测试{% endblock %}
{% load staticfiles %}
{% load case_tags %}

{% block content %}
    <div class="wrap case">
        <div class="header clearfix">
            <div class="title fl">
                <h2>{{ case.name }}</h2>
            </div>
        </div>
        <!--添加case内容开始-->
        <div class="section case-add">
            <div class="title">
                <span class="pts-icon circle"></span>
                编辑测试用例
            </div>
            <form method="post" id="case_add_form">
                <!--项目列表选项-->
                <p>
                    <label class="required" for="id_project">项&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;目:</label>
                    <select id="id_project" name="project" required="">
                        <option value="{{ case.project_id }}" selected>{{ case.project.name }}</option>
                    </select>
                </p>

                <!--测试用例名称-->
                <p>
                    <label for="id_name">用例名称:</label>
                    <input id="id_name" maxlength="100" name="name" type="text" value="{{ case.name }}" required="">
                    {% csrf_token %}
                </p>

                <!--测试用例描述-->
                <p>
                    <label for="id_desc" class="label-block">描&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;述:</label>
                    <!--<input id="id_desc" maxlength="512" name="desc" type="text" value="">-->
                    <textarea cols="60" id="id_desc" maxlength="512" name="desc" rows="3"
                        ondblclick="this.focus();this.select();"
                        placeholder="测试用例描述信息">{{ case.desc }}</textarea>
                </p>

                <!--选择编写方式-->
                <p>
                    <label class="required" for="id_way">编码方式:</label>
                    <select id="id_way" name="way" required="">
                        <option value="shiwu"
                                {% ifequal  'shiwu' case.way %}selected="selected"{% endifequal %}>事务</option>
                        <option value="code"
                            {% ifequal  'code' case.way %}selected="selected"{% endifequal %}>代码</option>
                    </select>
                    <span class="hint">
                        只能使用一种方式
                    </span>
                </p>
                <div class="code-way">
                    <label class="label-block" >事务列表:</label>
                    <ol class="shiwu-list">
                        {% for shiwu in case.shiwu_set.all %}
                            <li class="clearfix">
                                <input class="shiwu" name="shiwu" value="{{ shiwu.id }}" type="checkbox" checked>
                                <span>{{ shiwu.name }}</span>
                                <div class="buttons fr">
                                    <div class="btn btn-default" onclick="removeShiwu(this);">移出</div>
                                    <div class="btn btn-primary" onclick="editShiwu(this);">编辑</div>
                                </div>
                            </li>
                        {% endfor %}
                     </ol>
                    {% if case.shiwu_set %}
                        <div class="add-shiwu" style="padding-bottom: 20px;">
                            <span>测试用例事务</span>
                            <span><a class="plus" onclick="showShiwuMask();">+</a>一个</span>
                        </div>
                    {% else %}
                        <div class="add-shiwu">
                            <span>还没有任何事务</span>
                            <span><a class="plus" onclick="showShiwuMask();">+</a>一个</span>
                        </div>
                    {% endif %}

                </div>

                <!--测试代码-->
                <div class="code-way">
                    <label for="id_code" class="label-block">测试代码:</label>
                    <textarea cols="60" id="id_code" name="code" rows="16"
                              placeholder="请输入测试的代码">{{ case.code }}</textarea>
                </div>

                <!--用例状态：edit可见-->
                <p>
                    <label class="required" for="id_status">状&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;态:</label>
                    <select id="id_status" name="status" required="">
                        {% for status in status_choices %}
                            <option value="{{ status.0 }}" {% ifequal status.0 case.status %}selected="selected" {% endifequal %}>{{ status.1 }}</option>
                        {% endfor %}

                    </select>
                </p>

                <!--用例最近执行：edit可见-->
                <p>
                    <label for="id_execute_id">最近执行:</label>
                    <input id="id_execute_id" name="execute_id" type="text" value="20" disabled="true" value="{{ case.execute_id }}">
                </p>

                <!--用例Cookie-->
                <p>
                    <label for="id_cookies" class="label-block">Cookies:</label>
                    <!--<input id="id_cookies" maxlength="512" name="cookies" type="text" value="">-->
                    <textarea cols="60" id="id_cookies" name="cookies" rows="1"
                        ondblclick="this.focus();this.select()"
                        placeholder="请输入cookies:PHPSESSID=xxxx;route=xxxxx">{{ case.cookies }}</textarea>
                </p>

                <!--提交按钮组-->
                <div class="buttons">
                    <input type="reset" class="btn btn-default" value="重置">
                    <input type="submit" class="btn btn-primary" value="提交">
                </div>
            </form>
        </div>
        <!--添加case内容end-->
    </div>
{% endblock %}

{% block sidebar_right %}
    <!--获取项目最新的请求事务列表-->
    {% get_project_shiwu case.project_id request.user %}
{% endblock %}

{% block custom_mask %}
    <div class="mask mask-alert">

    </div>

    <div class="mask mask-shiwu">
        <div class="mask-wrap case">
            <div class="section clearfix">
                <div class="title fl">
                    <span class="pts-icon circle"></span>
                    添加事务
                </div>
                <div class="btn btn-default fr" id="mask-close">关闭</div>
                <div class="clear"></div>
                <form action="">
                    <!--项目列表选项-->
                    <p>
                        <label class="required" for="id_project2">项&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;目:</label>
                        <select id="id_project2" name="project" required="">
                            <option value="{{ case.project_id }}" selected>{{ case.project.name }}</option>
                        </select>
                    </p>
                    <!--事务名称-->
                    <p>
                        <label for="id_name2">事务名称:</label>
                        <input id="id_name2" maxlength="100" name="name" type="text" value="" required=""
                               placeholder="首页">
                        <label for="id_startup" style="width: 50px; margin-left: 10px;">Startup: </label>
                        <input type="checkbox" name="is_startup" id="id_startup" style="width:30px;">
                        {% csrf_token %}
                    </p>

                    <!--请求方法和网址-->
                    <p>
                        <select id="id_method" name="method" required="">
                            <option value="get" selected="selected">GET</option>
                            <option value="post">POST</option>
                            <option value="put">PUT</option>
                            <option value="delete">DELETE</option>
                        </select>
                        <input id="id_url" maxlength="120" name="url" type="text" value="" required=""
                               placeholder="请输入网址" style="margin-left: 0px;width:80%;line-height:20px;">
                    </p>

                    <!--数据可循环-->
                    <p>
                        <label for="id_cycle">数据可循环: </label>
                        <input type="checkbox" name="cycle" id="id_cycle" style="width:30px;" checked>
                    </p>

                    <!--请求Body-->
                    <div class="body-content clearfix">
                        <div class="body-title fl">请求Body:</div>
                        <div class="body-data fl">
                            <div class="box" style="">
                                <select name="type" id="">
                                    <option value="one" selected="selected">单值</option>
                                    <option value="many">多值</option>
                                    <option value="list">列表</option>
                                </select>
                                <input type="text" class="field" name="key" placeholder="key">
                                <a class="fieldDel btn btn-default" onclick="fieldDelClick(this);">Del</a>
                                <a class="fieldAdd btn btn-primary" onclick="fieldAddClick(this);">+</a>
                                <textarea class="field" name="value" placeholder="value"
                                    style="margin-left: 0px;margin-top: 5px;width: 575px;display: block;overflow-y: auto;"></textarea>

                            </div>
                        </div>
                    </div>

                    <!--提交按钮组-->
                    <div class="buttons">
                        <input type="reset" class="btn btn-default" value="重置">
                        <input type="submit" class="btn btn-primary" value="添加">
                    </div>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

{% block custom_js %}
    <script src="{% static 'js/zepto.min.js' %}"></script>
    <script src="{% static 'js/caseadd.js' %}"></script>
{% endblock %}

projects/webptspy/templates/case/view_shiwu.html
<div class="mask-wrap case">
    <div class="section clearfix">
        <div class="title fl">
            <span class="pts-icon circle"></span>
            查看事务【不可编辑】
        </div>
        <div class="btn btn-default fr" id="mask-alert-close" onclick="maskAlertClose();">关闭</div>
        <div class="clear"></div>
        <form disabled>
            <!--项目列表选项-->
            <p>
                <label class="required" for="id_project3">项&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;目:</label>
                <select id="id_project3" name="project" required="" disabled>
                        <option value="{{ shiwu.project_id }}">{{ shiwu.project.name }}</option>
                </select>
            </p>
            <!--事务名称-->
            <p>
                <label for="id_name3">事务名称:</label>
                <input id="id_name3" maxlength="100" name="name" type="text" value="{{ shiwu.name }}" required=""
                       placeholder="首页" disabled>
                <label for="id_startup" style="width: 50px; margin-left: 30px;">Startup: </label>
                <input type="checkbox" name="is_startup" id="id_startup" style="width:30px;" {% if shiwu.is_startup %}checked{% endif %} disabled>
                <span class="hint">创建者：{{ shiwu.user }}</span>
            </p>

            <!--请求方法和网址-->
            <p>
                <select id="id_method" name="method" required="" disabled>
                    {% for method in all_method %}
                        <option value="{{ method.0 }}" {% ifequal method.0 shiwu.method %}selected="selected"{% endifequal %}>{{ method.1 }}</option>
                    {% endfor %}
                </select>
                <input maxlength="120" name="url" type="text" value="{{ shiwu.url }}" required=""
                       placeholder="请输入网址" style="margin-left: 0px;width:80%;line-height:20px;" disabled>
            </p>

            <!--数据可循环-->
            <p>
                <label for="id_cycle">数据可循环: </label>
                <input type="checkbox" name="cycle" id="id_cycle" style="width:30px;"
                       {% if shiwu.cycle  %}checked{% endif %} disabled>
            </p>

            <!--请求Body-->
            <div class="body-content clearfix">
                <div class="body-title fl">请求Body:</div>
                <div class="body-data fl">
                    {% if body %}
                        {% for item in body %}
                            <div class="box" style="">
                                <select name="type" id="" disabled>
                                    {% for type_ in types %}
                                        <option value="{{ type_.0 }}" {% ifequal type_.0 item.0 %}selected="selected"{% endifequal %}>{{ type_.1 }}</option>
                                    {% endfor %}
                                </select>
                                <input type="text" class="field" name="key" placeholder="key" value="{{ item.1 }}" disabled>
                                <textarea class="field" name="value" style="margin-left: 0px;margin-top: 5px;width: 575px;display: block;overflow-y: auto;" disabled
                                          placeholder="value">{% if item.0 == "list" or item.0 == 'many' %}{% for i in item.2 %}{{ i }}{% endfor %}{% else %}{{ item.2 }}{% endif %}</textarea>
                             </div>
                        {% endfor %}
                    {% else %}
                        <div class="box" style="">
                                <select name="type" id="" disabled>
                                    <option value="one" selected="selected">单值</option>
                                    <option value="many">多值</option>
                                    <option value="list">列表</option>
                                </select>
                                <input type="text" class="field" name="key" placeholder="key" disabled>
                                <textarea class="field" name="value" placeholder="value"
                                    style="margin-left: 0px;margin-top: 5px;width: 575px;display: block;overflow-y: auto;" disabled></textarea>
                            </div>
                    {% endif %}
                </div>
            </div>

            <!--提交按钮组-->
            <div class="buttons">
{#                <input type="reset" class="btn btn-default" value="重置">#}
                <input class="btn btn-primary" value="克隆" onclick="cloneShiwu({{ shiwu.id }}, {{ request.user.pk }});">
            </div>
        </form>
    </div>
</div>