projects/webptspy/apps/account/urls.py
# -*- coding:utf-8 -*-
"""
用户相关的路由配置
"""
from django.conf.urls import url

from . import views

urlpatterns = [
    # 用户登录
    url(r'^login/', views.LoginView.as_view(), name='login'),
    # 退出登录
    url(r'^logout/', views.LogoutView.as_view(), name='logout'),
]

projects/webptspy/webpts/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from tproject.views.project import ProjectListView
from account.views import page_403, page_404, page_500


urlpatterns = [
    # 首页
    url(r'^$', ProjectListView.as_view(), name="index"),
    url(r'^admin/', admin.site.urls),
    # 项目相关的路由
    url(r'^project/', include('tproject.urls.project', namespace='project')),
    # 用户相关的路由
    url(r'^user/', include('account.urls', namespace='user')),
    # 网站api
    url(r'^api/1.0/', include('webpts.urls_api', namespace="api")),
    # 测试用例
    url(r'^case/', include('tcase.urls.case', namespace="case")),
    # execute相关的路由
    url(r'^execute/', include('tcase.urls.execute', namespace='execute')),
]


handler403 = page_403
handler404 = page_404
handler500 = page_500

projects/webptspy/templates/base.html
<!DOCTYPE html>
<html>
    {% load staticfiles %}
	<head>
		<meta charset="UTF-8">
		<title>{% block title %}性能测试{% endblock %}</title>
		<link rel="stylesheet" href="{% static 'css/normalize.css' %}" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
        {% block custom_css %}
        {% endblock %}
	</head>
	<body>
		<div class="container">
			<!--左边栏开始-->
			<div class="sidebar-left">
				<!--logo开始-->
                <a href="/" title="性能测试">
				<div class="logo">
						<img src="{% static 'images/logo.svg' %}" alt="" />
				</div>
                </a>
				<!--logo结束-->

                {% block nav_left %}
				<!--左边导航列表start-->
				<ul class="nav">
					<li><a href="{% url 'project:list' 1 %}">项目列表</a></li>
					<li><a href="{% url 'case:list' 1 %}">测试用例</a></li>
					<li><a href="{% url 'execute:report_list' 1 %}">报告列表</a></li>
				</ul>
				<!--左边导航列表end-->
                <div class="user-info">
                    {% if request.user.is_authenticated %}
                        <div class="user-logout">
                            <span>Hello {{ request.user.username }}</span>
                            <a href="{% url 'user:logout' %}">退出</a>
                        </div>
                    {% else %}
                        <div class="user-login">
                            <a href="{% url 'user:login' %}">登陆</a>
                        </div>
                    {% endif %}
                </div>
                {% endblock %}
			</div>
			<!--左边栏结束-->

			<!--右边主内容区开始-->
			<div class="main">
                {% block main %}
				<!--中间content开始-->
				<div class="content fl">
					{% block content %}
                    {% endblock %}
                </div>
				<!--右边sidebar开始-->
				<div class="sidebar fr">
					{% block sidebar_right %}

                    {% endblock %}
				</div>
				<!--右边sidebar end-->
                {% endblock %}
			</div>
			<!--右边主内容区end-->
		</div>
        </div>
		<!--底部内容开始-->
		<div class="footer">
			<div class="copyright">
				Copyright @ 2011-2016 www.codelieche.com all Rights Reserved
				<br />
				<a href="http://www.miibeian.gov.cn">粤ICP备xxxxxxxxx号</a>

			</div>
		</div>
		<!--底部内容end-->

        <!--自定义的遮罩内容-->
        {% block custom_mask %}
        {% endblock %}

	</body>

	{% block custom_js %}
    {% endblock %}
</html>

projects/webptspy/templates/index.html
{% extends 'base.html' %}
{% block title %}首页 | 性能测试{% endblock %}
{% block  content %}

    <h1>This is <a href="{% url 'tcase:index' %}">index</a></h1>
    <a href="{% url 'api:execute:detail' 1 %}">execute 1的detail</a>
    {% if request.user.is_authenticated %}
        <h2>
            Hello {{ request.user.username }}
            <a href="/user/logout/">Logout</a>
        </h2>
    {% else %}
        <h2>
            <a href="{% url 'user:login' %}">Login</a>
        </h2>
    {% endif %}

{% endblock %}